-- Seed Data: Millennium Problems
-- Populates the millennium_problems table with the 7 official problems

INSERT INTO public.millennium_problems (
  slug, title, short_title, field, year, status, solver, solver_year, prize,
  description_simple, description_intermediate, description_advanced,
  clay_paper_author, clay_paper_year, clay_paper_url
) VALUES
(
  'pvsnp',
  'P versus NP Problem',
  'P vs NP',
  'Ciencias de la Computación',
  2000,
  'unsolved',
  NULL,
  NULL,
  '$1,000,000',
  'Si es fácil verificar que una solución es correcta, ¿también es fácil encontrar esa solución?',
  '¿Pueden los problemas cuyas soluciones se verifican rápidamente ser resueltos también rápidamente?',
  '¿Es toda decisión cuya respuesta puede ser verificada rápidamente por una máquina de Turing determinística también solucionable rápidamente?',
  'Stephen Cook',
  2000,
  'https://www.claymath.org/wp-content/uploads/2022/06/pvsnp.pdf'
),
(
  'riemann',
  'Riemann Hypothesis',
  'Hipótesis de Riemann',
  'Teoría de Números',
  1859,
  'unsolved',
  NULL,
  NULL,
  '$1,000,000',
  'Los números primos siguen un patrón oculto relacionado con una función matemática especial.',
  'Todos los ceros no triviales de la función zeta de Riemann tienen parte real igual a 1/2.',
  'Todos los ceros no triviales de ζ(s) se encuentran en la línea crítica Re(s) = 1/2.',
  'Enrico Bombieri',
  2000,
  'https://www.claymath.org/millennium-problems/riemann-hypothesis/'
),
(
  'navier-stokes',
  'Navier-Stokes Existence and Smoothness',
  'Navier-Stokes',
  'Ecuaciones Diferenciales Parciales',
  1822,
  'unsolved',
  NULL,
  NULL,
  '$1,000,000',
  '¿Las ecuaciones que describen el flujo de fluidos siempre tienen soluciones suaves?',
  '¿Existen soluciones suaves y globales para las ecuaciones de Navier-Stokes en 3D?',
  'Probar o refutar la existencia de soluciones C∞ globales para las ecuaciones de Navier-Stokes incompresibles en ℝ³.',
  'Charles L. Fefferman',
  2000,
  'https://www.claymath.org/millennium-problems/navier-stokes-equation/'
),
(
  'yang-mills',
  'Yang-Mills and Mass Gap',
  'Yang-Mills',
  'Física Matemática',
  1954,
  'unsolved',
  NULL,
  NULL,
  '$1,000,000',
  '¿Por qué las partículas cuánticas tienen masa cuando la teoría dice que no deberían?',
  'Probar que existe un gap de masa positivo en la teoría cuántica de Yang-Mills.',
  'Demostrar la existencia matemática rigurosa de la teoría cuántica de campos de Yang-Mills en ℝ⁴ con un mass gap Δ > 0.',
  'Arthur Jaffe, Edward Witten',
  2000,
  'https://www.claymath.org/millennium-problems/yang-mills-and-mass-gap/'
),
(
  'hodge',
  'Hodge Conjecture',
  'Conjetura de Hodge',
  'Geometría Algebraica',
  1950,
  'unsolved',
  NULL,
  NULL,
  '$1,000,000',
  '¿Se pueden describir formas geométricas complejas usando ecuaciones algebraicas?',
  'Las clases de cohomología de tipo (p,p) son combinaciones de clases de ciclos algebraicos.',
  'Para variedades algebraicas proyectivas no singulares, toda clase de Hodge es una combinación racional de clases de ciclos algebraicos.',
  'Pierre Deligne',
  2000,
  'https://www.claymath.org/millennium-problems/hodge-conjecture/'
),
(
  'birch-sd',
  'Birch and Swinnerton-Dyer Conjecture',
  'Birch & Swinnerton-Dyer',
  'Teoría de Números',
  1960,
  'unsolved',
  NULL,
  NULL,
  '$1,000,000',
  'Relaciona puntos en curvas con funciones especiales que codifican información aritmética.',
  'El rango de una curva elíptica es igual al orden del cero de su función L en s=1.',
  'Para una curva elíptica E sobre ℚ: rank(E(ℚ)) = ord_{s=1} L(E,s).',
  'Andrew Wiles',
  2000,
  'https://www.claymath.org/wp-content/uploads/2022/05/birchswin.pdf'
),
(
  'poincare',
  'Poincaré Conjecture',
  'Conjetura de Poincaré',
  'Topología',
  1904,
  'solved',
  'Grigori Perelman',
  2003,
  'Resuelto (premio rechazado)',
  'Toda forma 3D sin agujeros que se comporta como una esfera, es una esfera.',
  'Toda 3-variedad compacta simplemente conexa es homeomorfa a la 3-esfera.',
  'Toda variedad compacta de dimensión 3 simplemente conexa es homeomorfa a S³.',
  'John Milnor',
  2000,
  'https://www.claymath.org/millennium-problems/poincare-conjecture/'
)
ON CONFLICT (slug) DO NOTHING;
